# Site
repository: mehranus/resumus
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mehran Behnam
title: Software Engineer
email: mehranbehnam77@gmail.com
website: mehranbehnam.ir

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: mehranbehnam77
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
 icon: fas fa-blog
 url: http://blog.mehranbehnam.ir
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A Software engineer with experience of working in distributed and scalable projects like real-time chat and financial services, working knowledge of agile methodology, passion for learning Cloud Native patterns, algorithms, concurrency models.

  I am most skilled in: <mark>java</mark> and <mark>Eating Pizza</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: VASL Solutions
        link: vasl.ir
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: September 2019 - present

        description: | # this will include new lines to allow paragraphs
          - Developed a new version of  BaaS with modular architecture from scratch
          - My favorite part of the aforementioned project was the fact that I was able to customize our software for enterprise businesses rapidly and easily using a modular architecture.
          - Developed new Software functionalities ensuring that clients’ vision and requirements were met.
          - Developed all modules, services and create all CI/CDs from build to deploy on stage and production server.
          - Developed a simple user behavior tracker.
          - Techs: Java, SpringBoot, Docker, Kafka, MongoDB, Redis, Elasticsearch


      - layout: left
        title: Jibit
        link: jibit.ir
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: April 2018 - April 2019
        description: | # this will include new lines to allow paragraphs
          - Developed a game-changer internet payment gateway from scratch
          in this IPG that we called QRPG, you didn't need to use your card information, you just need to scan a QR code and pay it with your Jibit credit.
          - Developed some services on microservice architecture.
          - Contribution in decisions for architecture and design of the project.
          - Verifying the expected application behavior using automated tests.
          - Techs: Java, Redis, Docker, MySQL, GitLab CI/CD, NGINX, ELK, golang


      - layout: left
        title: Retain.ir
        link: Retain.ir
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: August 2017 - April 2018
        description: | # this will include new lines to allow paragraphs
          - Retain is a leading SASS live support solution based in Tehran, Iran. As a Back-end Engineer, my core activities were:
          - Creating new features, functionalities, and capabilities on the software’s core back-end by using PHP, Laravel, and other related technologies.
          - Recommending solutions for a streamlined, user-friendly interface with the design team.
          - Techs: PHP, MySQL, RabbitMQ, Laravel, MongoDB, Git, NGINX.
      - layout: left
        title: Wphelper.ir
        link: Wphelper.ir
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: December 2016 - August 2107
        description: | # this will include new lines to allow paragraphs
          - Developed & helped other developers create high quality and well designed
          - plugins and themes for around 300 WordPress installations.
          - Techs: PHP, MySQL, wordpress, etc.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PNU - North Tehran Branch
        caption: 2010 - 2013
        sub_title: BSc Software Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests software engineering some of my other interests and hobbies are:
      - Online Gaming 🎮
      - Nature 🌳 🌲
      - Music 🎵 🎹 🎼
      - Hiking 🥾

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
